
const data = [
    {
      id:'01',
      img: "https://m.media-amazon.com/images/I/71dgWKs5JgL._SX679_.jpg",
      // img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw5460fdbb/images/Titan/Catalog/1733KL03_1.jpg?sw=360&sh=360",
      title: "Titan Quartz Multifunction Blue Dial Leather Strap Watch for Men",
      reviews: "123 reviews",
      price: '₹ 3,095.00',
      company: "Titan",
      color: "white",
      category: "analog",
      featuredata: true,
    },
    {
      id:'02',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwaa03e7d8/images/Titan/Catalog/2608YM01_1.jpg?sw=800&sh=800",
      title: "Titan Raga Viva Champagne Dial Women Watch With Metal Strap",
      reviews: "123 reviews",
      price: '₹ 5,795.00',
      company: "Titan",
      color: "gold",
      gender: 'female',
      category: "analog",
    },
    {
      id:'03', 
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwed38bfc8/images/Titan/Catalog/2642WM01_1.jpg?sw=800&sh=800",
      title: "Raga Women's Viva Trendsetter Rose Gold Watch",
      reviews: "2 reviews",
      price: "₹ 5,485.00",
      company: "Titan",
      color: "Rose Gold",
      gender: 'female',
      category: "analog",
    },
    {
      id:'04',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw060b076b/images/Titan/Catalog/2724WM01_1.jpg?sw=800&sh=800",
      title: "Titan Raga Rose Gold Dial Watch for Women",
      reviews: "123 reviews",
      price: "₹ 3,995.00",
      company: "Titan",
      color: "Rose Gold",
      gender: 'female',
      category: "analog",
      featuredata: true,
    },
    {
      id:'05',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwa4ee95f4/images/Titan/Catalog/2725WM01_2.jpg?sw=800&sh=800",
      title: "Titan Raga Rose Gold Dial Watch for Women",
      reviews: "36 reviews",
      price: "₹ 3,995.00",
      company: "Titan",
      color: "Rose Gold",
      gender: 'female',
      category: "analog",
    },
    {
      id:'06',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwf8bcd99c/images/Titan/Catalog/2656WM01_2.jpg?sw=800&sh=800",
      title: "Titan Women's Lagan Watch: Rose Gold Accents & Refined Elegance",
      reviews: "195 reviews",
      price: "₹ 2,835.00",
      company: "Titan",
      color: "Rose Gold",
      gender: 'female',
      category: "analog",
    },
    {
      id:'07',
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw5f6c1e8c/images/Fastrack/Catalog/3227SL01_1.jpg?sw=800&sh=800",
      title: "Fastrack Fastfit Quartz Multifunction Black Dial Leather Strap Watch for Guys",
      reviews: "7 reviews",
      price: "₹ 4,795.00",
      company: "Fastrack",
      color: "black",
      gender: 'male',
      category: "multifunction",
    },
    {
      id:'08',  
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw593f5c86/images/Fastrack/Catalog/3224NL01_1.jpg?sw=800&sh=800",
      title: "Fastrack Fastfit Quartz Analog with Day and Date Black Dial Leather Strap Watch for Guys",
      reviews: "26 reviews",
      price: "₹ 5,095.00",
      company: "Fastrack",
      color: "black",
      gender: 'male',
      category: "Analog",
    },
    {
      id:'09', 
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwdfe07fac/images/Fastrack/Catalog/3225KP01_1.jpg?sw=800&sh=800",
      title: "Fastrack Fastfit Quartz Analog Black Dial Silicone Strap Watch for Guys",
      reviews: "9 reviews",
      price: "₹ 2,425.00",
      company: "Fastrack",
      color: "Black",
      gender: 'male',
      category: "Analog",
    },
    {
      id:'10',  
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw083dcbff/images/Fastrack/Catalog/38022PP03J_1.jpg?sw=800&sh=800",
      title: "Fastrack Quartz Analog Black Dial Plastic Strap Watch for Unisex",
      reviews: "0 reviews",
      price: "₹ 510.00",
      company: "Fastrack",
      color: "Black",
      gender: 'unisex',
      category: "Analogg",
    },
    {
      id:'11',  
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwd94c09fc/images/Fastrack/Catalog/68012PP14_1.jpg?sw=800&sh=800",
      title: "Fastrack Fastfit Quartz Analog Black Dial Silicone Strap Unisex Watch",
      reviews: "59 reviews",
      price: "₹ 695.00",
      company: "Fastrack",
      color: "Black",
      gender: 'unisex',
      category: "Analog",
      featuredata: true,
    },
    {
      id:'12',  
      img: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw08795a5f/images/Fastrack/Catalog/68011PP08_1.jpg?sw=800&sh=800",
      title: "Fastrack Fastfit Quartz Analog Grey Dial Silicone Strap Unisex Watch",
      reviews: "0 reviews",
      prevPrice: "$140,00",
      price: " ₹ 950.00",
      company: "fastrack",
      color: "Grey",
      gender: 'unisex',
      category: "Analog",
      featuredata: true,
    },
    {
      id:'13',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw42934c37/images/Titan/Catalog/2606WL01_1.jpg?sw=800&sh=800",
      title: "Titan Raga Viva Rose Gold Dial Women Watch With Leather Strap",
      reviews: "0 reviews",
      price: " ₹ 3,845.00",
      company: "Titan",
      color: "Rose Gold",
      gender: 'female',
      category: "Analog",
      featuredata: true,
    },
    {
      id:'14',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw5c1168ee/images/Titan/Catalog/90148KD02_1.jpg?sw=800&sh=800",
      title: "Titan Ceramic Fusion Quartz Multifunction Blue Dial Silver Dual-Toned Stainless Steel Bracelet Watch for Men",
      reviews: "0 reviews",
      price: " ₹ 19,475.00",
      company: "Titan",
      color: "blue",
      gender: 'male',
      category: "Multifunction",
    },
    {
      id:'15',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dweafe2698/images/Titan/Catalog/1733KM03_1.jpg?sw=800&sh=800",
      title: "Titan Men's Metropolitan Luxe: Multifunction Black Dial with Two-Tone Stainless Steel Bracelet Watch",
      reviews: "0 reviews",
      price: " ₹ 7,495.00",
      company: "Titan",
      color: "Black",
      gender: 'male',
      category: "Multifunction",
    },
    {
      id:'16',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw768cd5db/images/Titan/Catalog/1825YM12_2.jpg?sw=800&sh=800",
      title: "Titan Karishma Quartz Analog Champagne Dial Stainless Steel Strap Watch for Men",
      reviews: "0 reviews",
      price: "  ₹ 3,545.00",
      company: "Titan",
      color: "Champagne",
      gender: 'male',
      category: "analog",
    },
    {
      id:'17',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwfde8e8ca/images/Titan/Catalog/1734KM02_1.jpg?sw=800&sh=800",
      title: "Titan Men's Metropolitan Luxe: Multifunction White Dial with Two-Tone Stainless Steel Bracelet Watch",
      reviews: "0 reviews",
      price: "₹ 7,925.00",
      company: "Titan",
      color: "white",
      gender: 'male',
      category: "analog",
    },
    {
      id:'18', 
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw5d2363e7/images/Titan/Catalog/1638SL02_1.jpg?sw=800&sh=800",
      title: "Titan Karishma Zing Quartz Analog Black Dial Leather Strap Watch for Men",
      reviews: "0 reviews",
      price: "₹ 1,795.00",
      company: "Titan",
      color: "black",
      gender: 'male',
      category: "analog",
    },
    {
      id:'19',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw03992e91/images/Titan/Catalog/1644SL01_2.jpg?sw=800&sh=800",
      title: "Titan Karishma Zing Quartz Analog Brown Dial Leather Strap Watch for Men",
      reviews: "7 reviews",
      price: "₹ 1,845.00",
      company: "Titan",
      color: "brown",
      gender: 'male',
      category: "analog",
      featuredata: true,
    },
    {
      id:'20',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwd8767fbc/images/Fastrack/Catalog/38091PP01_1.jpg?sw=800&sh=800",
      title: "Fastrack Reflex Invoke Smartwatch Black: BT Calling, Advanced Chipset, Breathing Rate, IP68",
      reviews: "7 reviews",
      price: "₹ 2,995.00",
      company: "Fastrack",
      color: "black",
      category: "Smartwatch",
      featuredata: true,
    },
    {
      id:'21',  
      img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwe228bb40/images/Fastrack/Catalog/38079PP04_1.jpg?sw=800&sh=800",
        // img: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwe228bb40/images/Fastrack/Catalog/38079PP04_1.jpg?sw=800&sh=800",
      title: "Fastrack Reflex Hello Pink: HD Smartwatch with AI Voice & Hydration Alerts",
      reviews: "69 reviews",
      price: "₹ 1,999.00",
      company: "Fastrack",
      color: "Pink",
      gender: 'female',
      category: "Smartwatch",
      featuredata: true,
    },
];
export default data; 